project:
  type: book
  output-dir: docs

book:
  title: "Null Hypothesis Significance Testing in Psychology"
  author: "Garrett D. Greeley, Ph.D."
  date: "4/14/2026"
  chapters:
    - index.qmd
    #- chapters/intro.qmd
    - chapters/02-setup.qmd
    - chapters/03-probability.qmd
    - chapters/04-ztests.qmd
    - chapters/05-hypothesis-testing.qmd
    - chapters/06-ttests-1.qmd
    #- chapters/07-ttests-2.qmd
    - chapters/08-anova.qmd
    - chapters/08_5-anova-2.qmd
    - chapters/09-correlation.qmd
    - chapters/10-regression.qmd
    #- chapters/0x-advanced-topics.qmd
    - chapters/summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - lux
      - brand
  pdf:
    documentclass: scrreprt



